# The file is generated. Don't modify manually. Run `make manifests` to regenerate.

[project]
name = "perde-yaml"
repository = "https://github.com/yushiomote/perde"

[build-system]
requires = ["maturin"]
build-backend = "maturin"
